name: scb-to-moneywiz CI Pipeline

# events that trigger the workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# jobs to run
jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8 linter
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12, 3.13]
        
    steps:
      - uses: actions/checkout@v4
      - name: Read .python-version
        id: set-python-version
        run: |
          if [ -f .python-version ]; then
            echo "python_version=$(cat .python-version)" >> $GITHUB_OUTPUT
          else
            echo "python_version=3.12" >> $GITHUB_OUTPUT
          fi
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          if ls tests/test_*.py 1> /dev/null 2>&1; then
            pytest
          else
            echo "No tests found. Skipping tests."
          fi

  build:
    runs-on: ubuntu-latest
    needs: [linters, test]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t scb-to-moneywiz:latest .

